[mcp_servers.cloudflare-server]
command = "cmd"
args = [
    "/c",
    "npx -y @cloudflare/mcp-server-cloudflare run %CLOUDFLARE_ACCOUNT_ID%",
]

[mcp_servers.github-server]
command = "cmd"
args = [
    "/c",
    'set GITHUB_PERSONAL_ACCESS_TOKEN=%GITHUB_TOKEN% && C:\Users\ADMIN\Music\new-mun\intellihire-v3\.bin\github-mcp-server.exe stdio',
]
