name = "intellihire-v3"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "intellihire_db"
database_id = "a73d035b-1328-4eee-8e94-91db4c78f0f2"

# R2 Object Storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "intellihire-uploads"

# KV Namespaces
[[kv_namespaces]]
binding = "SESSION_STORE"
id = "2fb07ec6e55048d4880d24dd9e4b6c8f"

# Workers AI
[ai]
binding = "AI"

# Routes / Domain
routes = [
  { pattern = "intellihire.is-a.dev/*", zone_name = "is-a.dev" }
]
